{"cvrfdoc":{"document_title":"Red Hat Enhancement Advisory: python-rtslib bug fix and enhancement update","document_distribution":"Copyright Â© 2021 Red Hat, Inc. All rights reserved.","document_references":{"reference":[{"description":"https://access.redhat.com/errata/RHEA-2020:4505","type":"Self","url":"https://access.redhat.com/errata/RHEA-2020:4505"},{"description":"https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.3_release_notes/index","type":"External","url":"https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.3_release_notes/index"}]},"aggregate_severity":"","document_tracking":{"initial_release_date":"2020-11-04T02:15:00Z","identification":{"id":"RHEA-2020:4505"},"revision_history":{"revision":{"date":"2020-12-10T16:30:00Z","number":"1","description":"Current version"}},"generator":{"date":"2021-10-13T16:26:00Z","engine":"Red Hat SDEngine 3.2.0"},"current_release_date":"2020-12-10T16:30:00Z","version":"1","status":"Final"},"product_tree":{"relationship":[{"relates_to_product_reference":"BaseOS-8.3.0.GA","product_reference":"python-rtslib-0:2.1.73-2.el8","full_product_name":{"product_id":"BaseOS-8.3.0.GA:python-rtslib-0:2.1.73-2.el8","cpe":"cpe:/o:redhat:enterprise_linux:8::baseos","product_name":"python-rtslib-0:2.1.73-2.el8 as a component of Red Hat Enterprise Linux BaseOS (v. 8)"},"relation_type":"Default Component Of"}],"branch":[{"name":"Red Hat Enterprise Linux","type":"Product Family","branch":[{"name":"Red Hat Enterprise Linux BaseOS (v. 8)","full_product_name":{"product_id":"BaseOS-8.3.0.GA","cpe":"cpe:/o:redhat:enterprise_linux:8::baseos","product_name":"Red Hat Enterprise Linux BaseOS (v. 8)"},"type":"Product Name"}]},{"name":"python-rtslib-0:2.1.73-2.el8","full_product_name":{"product_id":"python-rtslib-0:2.1.73-2.el8","cpe":"cpe:/o:redhat:enterprise_linux:8::baseos","product_name":"python-rtslib-2.1.73-2.el8.src.rpm"},"type":"Product Version"}]},"document_publisher":{"issuing_authority":"Red Hat Product Security","contact_details":"secalert@redhat.com","type":"Vendor"},"vulnerability":[{"notes":{"note":"python-rtslib: weak permissions for /etc/target/saveconfig.json"},"cve":"CVE-2020-14019","references":{"reference":[{"description":"CVE-2020-14019","url":"https://access.redhat.com/security/cve/CVE-2020-14019"},{"description":"bz#1854723: CVE-2020-14019 python-rtslib: weak permissions for /etc/target/saveconfig.json","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1854723"}]},"release_date":"2020-06-19T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["BaseOS-8.3.0.GA:python-rtslib-0:2.1.73-2.el8"],"type":"Fixed"}},"remediations":{"remediation":{"description":"Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\nFor details on how to apply this update, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHEA-2020:4505"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2020-06-19T00:00:00Z","ordinal":"1"}],"document_notes":{"note":["An update for python-rtslib is now available for Red Hat Enterprise Linux\n8.","For detailed information on changes in this release, see the Red Hat\nEnterprise Linux 8.3 Release Notes linked from the References section.","This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original."]},"document_type":"Security Advisory"}}