{"cvrfdoc":{"document_title":"Red Hat Security Advisory: python39:3.9 and python39-devel:3.9 security update","document_distribution":"Copyright © 2021 Red Hat, Inc. All rights reserved.","document_references":{"reference":[{"description":"https://access.redhat.com/errata/RHSA-2021:4160","type":"Self","url":"https://access.redhat.com/errata/RHSA-2021:4160"},{"description":"https://access.redhat.com/security/updates/classification/#moderate","type":"External","url":"https://access.redhat.com/security/updates/classification/#moderate"},{"description":"https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.5_release_notes/","type":"External","url":"https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.5_release_notes/"}]},"aggregate_severity":"Moderate","document_tracking":{"initial_release_date":"2021-11-09T18:32:00Z","identification":{"id":"RHSA-2021:4160"},"revision_history":{"revision":{"date":"2021-11-09T18:32:00Z","number":"1","description":"Current version"}},"generator":{"date":"2021-11-09T21:43:00Z","engine":"Red Hat SDEngine 3.3.0"},"current_release_date":"2021-11-09T18:32:00Z","version":"1","status":"Final"},"product_tree":{"relationship":[{"relates_to_product_reference":"AppStream-8.5.0.GA","product_reference":"python39:3.9-8050020210811100211.d428a79b","full_product_name":{"product_id":"AppStream-8.5.0.GA:python39:3.9-8050020210811100211.d428a79b","cpe":"cpe:/a:redhat:enterprise_linux:8::appstream","product_name":"python39:3.9-8050020210811100211.d428a79b as a component of Red Hat Enterprise Linux AppStream (v. 8)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"CRB-8.5.0.GA","product_reference":"python39-devel:3.9-8050020210811100211.d428a79b","full_product_name":{"product_id":"CRB-8.5.0.GA:python39-devel:3.9-8050020210811100211.d428a79b","cpe":"cpe:/a:redhat:enterprise_linux:8::crb","product_name":"python39-devel:3.9-8050020210811100211.d428a79b as a component of Red Hat Enterprise Linux CRB (v. 8)"},"relation_type":"Default Component Of"}],"branch":[{"name":"Red Hat Enterprise Linux","type":"Product Family","branch":[{"name":"Red Hat Enterprise Linux AppStream (v. 8)","full_product_name":{"product_id":"AppStream-8.5.0.GA","cpe":"cpe:/a:redhat:enterprise_linux:8::appstream","product_name":"Red Hat Enterprise Linux AppStream (v. 8)"},"type":"Product Name"},{"name":"Red Hat Enterprise Linux CRB (v. 8)","full_product_name":{"product_id":"CRB-8.5.0.GA","cpe":"cpe:/a:redhat:enterprise_linux:8::crb","product_name":"Red Hat Enterprise Linux CRB (v. 8)"},"type":"Product Name"}]},{"name":"python39-devel:3.9-8050020210811100211.d428a79b","full_product_name":{"product_id":"python39-devel:3.9-8050020210811100211.d428a79b","cpe":"cpe:/a:redhat:enterprise_linux:8::crb","product_name":"python39-devel-3.9-8050020210811100211.d428a79b"},"type":"Product Version"},{"name":"python39:3.9-8050020210811100211.d428a79b","full_product_name":{"product_id":"python39:3.9-8050020210811100211.d428a79b","cpe":"cpe:/a:redhat:enterprise_linux:8::appstream","product_name":"python39-3.9-8050020210811100211.d428a79b"},"type":"Product Version"}]},"document_publisher":{"issuing_authority":"Red Hat Product Security","contact_details":"secalert@redhat.com","type":"Vendor"},"vulnerability":[{"notes":{"note":"python: Information disclosure via pydoc"},"cve":"CVE-2021-3426","references":{"reference":[{"description":"CVE-2021-3426","url":"https://access.redhat.com/security/cve/CVE-2021-3426"},{"description":"bz#1935913: CVE-2021-3426 python: Information disclosure via pydoc","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1935913"}]},"release_date":"2021-03-10T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["AppStream-8.5.0.GA:python39:3.9-8050020210811100211.d428a79b","CRB-8.5.0.GA:python39-devel:3.9-8050020210811100211.d428a79b"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:4160"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank David Schwörer (Fedora) for reporting this issue."}},"discovery_date":"2021-01-19T00:00:00Z","ordinal":"1"},{"notes":{"note":"python-pip: Incorrect handling of unicode separators in git references"},"cve":"CVE-2021-3572","references":{"reference":[{"description":"CVE-2021-3572","url":"https://access.redhat.com/security/cve/CVE-2021-3572"},{"description":"bz#1962856: CVE-2021-3572 python-pip: Incorrect handling of unicode separators in git references","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1962856"}]},"release_date":"2021-04-24T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["AppStream-8.5.0.GA:python39:3.9-8050020210811100211.d428a79b","CRB-8.5.0.GA:python39-devel:3.9-8050020210811100211.d428a79b"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:4160"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2021-05-19T00:00:00Z","ordinal":"2"},{"notes":{"note":"python: urllib: Regular expression DoS in AbstractBasicAuthHandler"},"cve":"CVE-2021-3733","references":{"reference":[{"description":"https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-14-final","url":"https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-14-final"},{"description":"https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-11-final","url":"https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-11-final"},{"description":"https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-10-final","url":"https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-10-final"},{"description":"https://docs.python.org/3.9/whatsnew/changelog.html#python-3-9-5-final","url":"https://docs.python.org/3.9/whatsnew/changelog.html#python-3-9-5-final"},{"description":"CVE-2021-3733","url":"https://access.redhat.com/security/cve/CVE-2021-3733"},{"description":"bz#1995234: CVE-2021-3733 python: urllib: Regular expression DoS in AbstractBasicAuthHandler","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1995234"}]},"release_date":"2021-08-10T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["AppStream-8.5.0.GA:python39:3.9-8050020210811100211.d428a79b","CRB-8.5.0.GA:python39-devel:3.9-8050020210811100211.d428a79b"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:4160"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2021-08-10T00:00:00Z","ordinal":"3"},{"notes":{"note":"python: urllib: HTTP client possible infinite loop on a 100 Continue response"},"cve":"CVE-2021-3737","references":{"reference":[{"description":"CVE-2021-3737","url":"https://access.redhat.com/security/cve/CVE-2021-3737"},{"description":"bz#1995162: CVE-2021-3737 python: urllib: HTTP client possible infinite loop on a 100 Continue response","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1995162"}]},"release_date":"2021-08-09T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["AppStream-8.5.0.GA:python39:3.9-8050020210811100211.d428a79b","CRB-8.5.0.GA:python39-devel:3.9-8050020210811100211.d428a79b"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:4160"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2021-08-09T00:00:00Z","ordinal":"4"},{"notes":{"note":"python-lxml: Missing input sanitization for formaction HTML5 attributes may lead to XSS"},"cve":"CVE-2021-28957","references":{"reference":[{"description":"CVE-2021-28957","url":"https://access.redhat.com/security/cve/CVE-2021-28957"},{"description":"bz#1941534: CVE-2021-28957 python-lxml: Missing input sanitization for formaction HTML5 attributes may lead to XSS","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1941534"}]},"release_date":"2021-03-21T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["AppStream-8.5.0.GA:python39:3.9-8050020210811100211.d428a79b","CRB-8.5.0.GA:python39-devel:3.9-8050020210811100211.d428a79b"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:4160"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2021-03-21T00:00:00Z","ordinal":"5"},{"notes":{"note":"python-ipaddress: Improper input validation of octal strings"},"cve":"CVE-2021-29921","references":{"reference":[{"description":"https://python-security.readthedocs.io/vuln/ipaddress-ipv4-leading-zeros.html","url":"https://python-security.readthedocs.io/vuln/ipaddress-ipv4-leading-zeros.html"},{"description":"CVE-2021-29921","url":"https://access.redhat.com/security/cve/CVE-2021-29921"},{"description":"bz#1957458: CVE-2021-29921 python-ipaddress: Improper input validation of octal strings","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1957458"}]},"release_date":"2021-04-30T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["AppStream-8.5.0.GA:python39:3.9-8050020210811100211.d428a79b","CRB-8.5.0.GA:python39-devel:3.9-8050020210811100211.d428a79b"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:4160"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2021-04-30T00:00:00Z","ordinal":"6"},{"notes":{"note":"python-urllib3: ReDoS in the parsing of authority part of URL"},"cve":"CVE-2021-33503","references":{"reference":[{"description":"https://github.com/advisories/GHSA-q2q7-5pp4-w6pg","url":"https://github.com/advisories/GHSA-q2q7-5pp4-w6pg"},{"description":"CVE-2021-33503","url":"https://access.redhat.com/security/cve/CVE-2021-33503"},{"description":"bz#1968074: CVE-2021-33503 python-urllib3: ReDoS in the parsing of authority part of URL","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1968074"}]},"release_date":"2021-06-01T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["AppStream-8.5.0.GA:python39:3.9-8050020210811100211.d428a79b","CRB-8.5.0.GA:python39-devel:3.9-8050020210811100211.d428a79b"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:4160"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2021-06-01T00:00:00Z","ordinal":"7"}],"document_notes":{"note":["An update for the python39:3.9 and python39-devel:3.9 modules is now available for Red Hat Enterprise Linux 8.\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.","Python is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\nSecurity Fix(es):\n* python: Information disclosure via pydoc (CVE-2021-3426)\n* python: urllib: Regular expression DoS in AbstractBasicAuthHandler (CVE-2021-3733)\n* python-lxml: Missing input sanitization for formaction HTML5 attributes may lead to XSS (CVE-2021-28957)\n* python-ipaddress: Improper input validation of octal strings (CVE-2021-29921)\n* python-urllib3: ReDoS in the parsing of authority part of URL (CVE-2021-33503)\n* python-pip: Incorrect handling of unicode separators in git references (CVE-2021-3572)\n* python: urllib: HTTP client possible infinite loop on a 100 Continue response (CVE-2021-3737)\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\nAdditional Changes:\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 8.5 Release Notes linked from the References section.","This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original."]},"document_type":"Security Advisory"}}