{"cvrfdoc":{"document_title":"Red Hat Security Advisory: Red Hat OpenStack Platform 16.2 (python-django20) security update","document_distribution":"Copyright Â© 2021 Red Hat, Inc. All rights reserved.","document_references":{"reference":[{"description":"https://access.redhat.com/errata/RHSA-2021:3490","type":"Self","url":"https://access.redhat.com/errata/RHSA-2021:3490"},{"description":"https://access.redhat.com/security/updates/classification/#moderate","type":"External","url":"https://access.redhat.com/security/updates/classification/#moderate"}]},"aggregate_severity":"Moderate","document_tracking":{"initial_release_date":"2021-09-15T13:41:00Z","identification":{"id":"RHSA-2021:3490"},"revision_history":{"revision":{"date":"2021-09-15T13:41:00Z","number":"1","description":"Current version"}},"generator":{"date":"2021-09-15T18:02:00Z","engine":"Red Hat SDEngine 3.0.2"},"current_release_date":"2021-09-15T13:41:00Z","version":"1","status":"Final"},"product_tree":{"relationship":[{"relates_to_product_reference":"8Base-RHOS-16.2","product_reference":"python-django20-0:2.0.13-16.el8ost.1","full_product_name":{"product_id":"8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1","cpe":"cpe:/a:redhat:openstack:16.2::el8","product_name":"python-django20-0:2.0.13-16.el8ost.1 as a component of Red Hat OpenStack Platform 16.2"},"relation_type":"Default Component Of"}],"branch":[{"name":"Red Hat OpenStack Platform","type":"Product Family","branch":[{"name":"Red Hat OpenStack Platform 16.2","full_product_name":{"product_id":"8Base-RHOS-16.2","cpe":"cpe:/a:redhat:openstack:16.2::el8","product_name":"Red Hat OpenStack Platform 16.2"},"type":"Product Name"}]},{"name":"python-django20-0:2.0.13-16.el8ost.1","full_product_name":{"product_id":"python-django20-0:2.0.13-16.el8ost.1","cpe":"cpe:/a:redhat:openstack:16.2::el8","product_name":"python-django20-2.0.13-16.el8ost.1.src.rpm"},"type":"Product Version"}]},"document_publisher":{"issuing_authority":"Red Hat Product Security","contact_details":"secalert@redhat.com","type":"Vendor"},"vulnerability":[{"notes":{"note":"django: Potential directory-traversal via archive.extract()"},"cve":"CVE-2021-3281","references":{"reference":[{"description":"CVE-2021-3281","url":"https://access.redhat.com/security/cve/CVE-2021-3281"},{"description":"bz#1919969: CVE-2021-3281 django: Potential directory-traversal via archive.extract()","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1919969"}]},"release_date":"2021-02-01T10:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:3490"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2021-01-25T00:00:00Z","ordinal":"1"},{"notes":{"note":"django: Potential directory traversal via ``admindocs``"},"cve":"CVE-2021-33203","references":{"reference":[{"description":"https://www.djangoproject.com/weblog/2021/jun/02/security-releases/","url":"https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"},{"description":"CVE-2021-33203","url":"https://access.redhat.com/security/cve/CVE-2021-33203"},{"description":"bz#1966251: CVE-2021-33203 django: Potential directory traversal via ``admindocs``","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1966251"}]},"release_date":"2021-06-02T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:3490"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2021-05-26T00:00:00Z","ordinal":"2"},{"notes":{"note":"django: Possible indeterminate SSRF, RFI, and LFI attacks since validators accepted leading zeros in IPv4 addresses"},"cve":"CVE-2021-33571","references":{"reference":[{"description":"https://www.djangoproject.com/weblog/2021/jun/02/security-releases/","url":"https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"},{"description":"CVE-2021-33571","url":"https://access.redhat.com/security/cve/CVE-2021-33571"},{"description":"bz#1966253: CVE-2021-33571 django: Possible indeterminate SSRF, RFI, and LFI attacks since validators accepted leading zeros in IPv4 addresses","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1966253"}]},"release_date":"2021-06-02T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["8Base-RHOS-16.2:python-django20-0:2.0.13-16.el8ost.1"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2021:3490"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2021-05-26T00:00:00Z","ordinal":"3"}],"document_notes":{"note":["An update for python-django20 is now available for Red Hat OpenStack\nPlatform 16.2 (Train).\nRed Hat Product Security has rated this update as having a security impact\nof Moderate. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available for each vulnerability from\nthe CVE link(s) in the References section.","Security Fix(es):\n* Potential directory-traversal via archive.extract() (CVE-2021-3281)\n* Potential directory traversal via ``admindocs`` (CVE-2021-33203)\n* Possible indeterminate SSRF RFI and LFI attacks since validators accepted\nleading zeros in IPv4 addresses (CVE-2021-33571)\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.","This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original."]},"document_type":"Security Advisory"}}