{"cvrfdoc":{"document_title":"Red Hat Security Advisory: rh-python36-python security, bug fix, and enhancement update","document_distribution":"Copyright Â© 2021 Red Hat, Inc. All rights reserved.","document_references":{"reference":[{"description":"https://access.redhat.com/errata/RHSA-2019:3725","type":"Self","url":"https://access.redhat.com/errata/RHSA-2019:3725"},{"description":"https://access.redhat.com/security/updates/classification/#moderate","type":"External","url":"https://access.redhat.com/security/updates/classification/#moderate"}]},"aggregate_severity":"Moderate","document_tracking":{"initial_release_date":"2019-11-06T09:47:00Z","identification":{"id":"RHSA-2019:3725"},"revision_history":{"revision":{"date":"2021-02-02T04:20:00Z","number":"1","description":"Current version"}},"generator":{"date":"2021-08-23T04:47:00Z","engine":"Red Hat SDEngine 3.0.0"},"current_release_date":"2021-02-02T04:20:00Z","version":"1","status":"Final"},"product_tree":{"relationship":[{"relates_to_product_reference":"6Server-RHSCL-3.3","product_reference":"rh-python36-python-0:3.6.9-2.el6","full_product_name":{"product_id":"6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","cpe":"cpe:/a:redhat:rhel_software_collections:3::el6","product_name":"rh-python36-python-0:3.6.9-2.el6 as a component of Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 6)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"6Workstation-RHSCL-3.3","product_reference":"rh-python36-python-0:3.6.9-2.el6","full_product_name":{"product_id":"6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","cpe":"cpe:/a:redhat:rhel_software_collections:3::el6","product_name":"rh-python36-python-0:3.6.9-2.el6 as a component of Red Hat Software Collections for Red Hat Enterprise Linux Workstation (v. 6)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"7Server-Alt-RHSCL-3.3","product_reference":"rh-python36-python-0:3.6.9-2.el7","full_product_name":{"product_id":"7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"rh-python36-python-0:3.6.9-2.el7 as a component of Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 7)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"7Server-RHSCL-3.3","product_reference":"rh-python36-python-0:3.6.9-2.el7","full_product_name":{"product_id":"7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"rh-python36-python-0:3.6.9-2.el7 as a component of Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 7)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"7Server-RHSCL-3.3-7.5.Z","product_reference":"rh-python36-python-0:3.6.9-2.el7","full_product_name":{"product_id":"7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"rh-python36-python-0:3.6.9-2.el7 as a component of Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.5)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"7Server-RHSCL-3.3-7.6.Z","product_reference":"rh-python36-python-0:3.6.9-2.el7","full_product_name":{"product_id":"7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"rh-python36-python-0:3.6.9-2.el7 as a component of Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.6)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"7Server-RHSCL-3.3-7.7.Z","product_reference":"rh-python36-python-0:3.6.9-2.el7","full_product_name":{"product_id":"7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"rh-python36-python-0:3.6.9-2.el7 as a component of Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.7)"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"7Workstation-RHSCL-3.3","product_reference":"rh-python36-python-0:3.6.9-2.el7","full_product_name":{"product_id":"7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"rh-python36-python-0:3.6.9-2.el7 as a component of Red Hat Software Collections for Red Hat Enterprise Linux Workstation (v. 7)"},"relation_type":"Default Component Of"}],"branch":[{"name":"Red Hat Software Collections","type":"Product Family","branch":[{"name":"Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 6)","full_product_name":{"product_id":"6Server-RHSCL-3.3","cpe":"cpe:/a:redhat:rhel_software_collections:3::el6","product_name":"Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 6)"},"type":"Product Name"},{"name":"Red Hat Software Collections for Red Hat Enterprise Linux Workstation (v. 6)","full_product_name":{"product_id":"6Workstation-RHSCL-3.3","cpe":"cpe:/a:redhat:rhel_software_collections:3::el6","product_name":"Red Hat Software Collections for Red Hat Enterprise Linux Workstation (v. 6)"},"type":"Product Name"},{"name":"Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 7)","full_product_name":{"product_id":"7Server-Alt-RHSCL-3.3","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 7)"},"type":"Product Name"},{"name":"Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 7)","full_product_name":{"product_id":"7Server-RHSCL-3.3","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"Red Hat Software Collections for Red Hat Enterprise Linux Server (v. 7)"},"type":"Product Name"},{"name":"Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.5)","full_product_name":{"product_id":"7Server-RHSCL-3.3-7.5.Z","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.5)"},"type":"Product Name"},{"name":"Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.6)","full_product_name":{"product_id":"7Server-RHSCL-3.3-7.6.Z","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.6)"},"type":"Product Name"},{"name":"Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.7)","full_product_name":{"product_id":"7Server-RHSCL-3.3-7.7.Z","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"Red Hat Software Collections for Red Hat Enterprise Linux Server EUS (v. 7.7)"},"type":"Product Name"},{"name":"Red Hat Software Collections for Red Hat Enterprise Linux Workstation (v. 7)","full_product_name":{"product_id":"7Workstation-RHSCL-3.3","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"Red Hat Software Collections for Red Hat Enterprise Linux Workstation (v. 7)"},"type":"Product Name"}]},{"name":"rh-python36-python-0:3.6.9-2.el6","full_product_name":{"product_id":"rh-python36-python-0:3.6.9-2.el6","cpe":"cpe:/a:redhat:rhel_software_collections:3::el6","product_name":"rh-python36-python-3.6.9-2.el6.src.rpm"},"type":"Product Version"},{"name":"rh-python36-python-0:3.6.9-2.el7","full_product_name":{"product_id":"rh-python36-python-0:3.6.9-2.el7","cpe":"cpe:/a:redhat:rhel_software_collections:3::el7","product_name":"rh-python36-python-3.6.9-2.el7.src.rpm"},"type":"Product Version"}]},"document_publisher":{"issuing_authority":"Red Hat Product Security","contact_details":"secalert@redhat.com","type":"Vendor"},"vulnerability":[{"notes":{"note":"python: DOS via regular expression catastrophic backtracking in apop() method in pop3lib"},"cve":"CVE-2018-1060","references":{"reference":[{"description":"https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-final","url":"https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-final"},{"description":"CVE-2018-1060","url":"https://access.redhat.com/security/cve/CVE-2018-1060"},{"description":"bz#1549191: CVE-2018-1060 python: DOS via regular expression catastrophic backtracking in apop() method in pop3lib","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1549191"}]},"release_date":"2018-03-14T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank the Python security response team for reporting this issue."}},"discovery_date":"2018-02-26T00:00:00Z","ordinal":"1"},{"notes":{"note":"python: DOS via regular expression backtracking in difflib.IS_LINE_JUNK method in difflib"},"cve":"CVE-2018-1061","references":{"reference":[{"description":"https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-final","url":"https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-final"},{"description":"CVE-2018-1061","url":"https://access.redhat.com/security/cve/CVE-2018-1061"},{"description":"bz#1549192: CVE-2018-1061 python: DOS via regular expression backtracking in difflib.IS_LINE_JUNK method in difflib","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1549192"}]},"release_date":"2018-03-14T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank the Python security response team for reporting this issue."}},"discovery_date":"2018-02-26T00:00:00Z","ordinal":"2"},{"notes":{"note":"python: Missing salt initialization in _elementtree.c module"},"cve":"CVE-2018-14647","references":{"reference":[{"description":"https://bugs.python.org/issue34623","url":"https://bugs.python.org/issue34623"},{"description":"CVE-2018-14647","url":"https://access.redhat.com/security/cve/CVE-2018-14647"},{"description":"bz#1631822: CVE-2018-14647 python: Missing salt initialization in _elementtree.c module","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1631822"}]},"release_date":"2018-09-22T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank the Python Security Response Team for reporting this issue."}},"discovery_date":"2018-09-21T00:00:00Z","ordinal":"3"},{"notes":{"note":"python: Integer overflow in Modules/_pickle.c allows for memory exhaustion if serializing gigabytes of data"},"cve":"CVE-2018-20406","references":{"reference":[{"description":"https://python-security.readthedocs.io/vuln/pickle-load-dos.html","url":"https://python-security.readthedocs.io/vuln/pickle-load-dos.html"},{"description":"CVE-2018-20406","url":"https://access.redhat.com/security/cve/CVE-2018-20406"},{"description":"bz#1664509: CVE-2018-20406 python: Integer overflow in Modules/_pickle.c allows for memory exhaustion if serializing gigabytes of data","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1664509"}]},"release_date":"2018-09-21T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Low","type":"Impact"}},"discovery_date":"2019-01-04T00:00:00Z","ordinal":"4"},{"notes":{"note":"python: Cookie domain check returns incorrect results"},"cve":"CVE-2018-20852","references":{"reference":[{"description":"CVE-2018-20852","url":"https://access.redhat.com/security/cve/CVE-2018-20852"},{"description":"bz#1740347: CVE-2018-20852 python: Cookie domain check returns incorrect results","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1740347"}]},"release_date":"2018-10-31T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2019-07-14T00:00:00Z","ordinal":"5"},{"notes":{"note":"python: NULL pointer dereference using a specially crafted X509 certificate"},"cve":"CVE-2019-5010","references":{"reference":[{"description":"https://python-security.readthedocs.io/vuln/ssl-crl-dps-dos.html","url":"https://python-security.readthedocs.io/vuln/ssl-crl-dps-dos.html"},{"description":"CVE-2019-5010","url":"https://access.redhat.com/security/cve/CVE-2019-5010"},{"description":"bz#1666519: CVE-2019-5010 python: NULL pointer dereference using a specially crafted X509 certificate","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1666519"}]},"release_date":"2019-01-15T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2019-01-15T00:00:00Z","ordinal":"6"},{"notes":{"note":"python: CRLF injection via the query part of the url passed to urlopen()"},"cve":"CVE-2019-9740","references":{"reference":[{"description":"CVE-2019-9740","url":"https://access.redhat.com/security/cve/CVE-2019-9740"},{"description":"bz#1688169: CVE-2019-9740 python: CRLF injection via the query part of the url passed to urlopen()","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1688169"}]},"release_date":"2019-03-13T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2019-03-13T00:00:00Z","ordinal":"7"},{"notes":{"note":"python: CRLF injection via the path part of the url passed to urlopen()"},"cve":"CVE-2019-9947","references":{"reference":[{"description":"CVE-2019-9947","url":"https://access.redhat.com/security/cve/CVE-2019-9947"},{"description":"bz#1695572: CVE-2019-9947 python: CRLF injection via the path part of the url passed to urlopen()","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1695572"}]},"release_date":"2019-03-23T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2019-03-28T00:00:00Z","ordinal":"8"},{"notes":{"note":"python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms"},"cve":"CVE-2019-9948","references":{"reference":[{"description":"CVE-2019-9948","url":"https://access.redhat.com/security/cve/CVE-2019-9948"},{"description":"bz#1695570: CVE-2019-9948 python: Undocumented local_file protocol allows remote attackers to bypass protection mechanisms","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1695570"}]},"release_date":"2019-03-23T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2019-03-28T00:00:00Z","ordinal":"9"},{"notes":{"note":"python: email.utils.parseaddr wrongly parses email addresses"},"cve":"CVE-2019-16056","references":{"reference":[{"description":"CVE-2019-16056","url":"https://access.redhat.com/security/cve/CVE-2019-16056"},{"description":"bz#1749839: CVE-2019-16056 python: email.utils.parseaddr wrongly parses email addresses","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1749839"}]},"release_date":"2018-07-19T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["6Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","6Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el6","7Server-Alt-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.5.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.6.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3-7.7.Z:rh-python36-python-0:3.6.9-2.el7","7Server-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7","7Workstation-RHSCL-3.3:rh-python36-python-0:3.6.9-2.el7"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes described in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2019:3725"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"discovery_date":"2019-09-06T00:00:00Z","ordinal":"10"}],"document_notes":{"note":["An update for rh-python36-python is now available for Red Hat Software Collections.\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.","Python is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\nThe following packages have been upgraded to a later upstream version: rh-python36-python (3.6.9). (BZ#1709344)\nSecurity Fix(es):\n* python: DOS via regular expression backtracking in difflib.IS_LINE_JUNK method in difflib (CVE-2018-1061)\n* python: Missing salt initialization in _elementtree.c module (CVE-2018-14647)\n* python: Cookie domain check returns incorrect results (CVE-2018-20852)\n* python: NULL pointer dereference using a specially crafted X509 certificate (CVE-2019-5010)\n* python: CRLF injection via the query part of the url passed to urlopen() (CVE-2019-9740)\n* python: CRLF injection via the path part of the url passed to urlopen() (CVE-2019-9947)\n* python: email.utils.parseaddr wrongly parses email addresses (CVE-2019-16056)\n* python: DOS via regular expression catastrophic backtracking in apop() method in pop3lib (CVE-2018-1060)\n* python: Integer overflow in Modules/_pickle.c allows for memory exhaustion if serializing gigabytes of data (CVE-2018-20406)\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\nBug Fix(es):\n* urlsplit doesn't accept a NFKD hostname with a port number (BZ#1709340)\n* rh-python36 cannot unpickle datetime.date objects (BZ#1749103)","This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original."]},"document_type":"Security Advisory"}}