{"cvrfdoc":{"document_title":"Red Hat Security Advisory: python-django security update","document_distribution":"Copyright Â© 2021 Red Hat, Inc. All rights reserved.","document_references":{"reference":[{"description":"https://access.redhat.com/errata/RHSA-2020:4390","type":"Self","url":"https://access.redhat.com/errata/RHSA-2020:4390"},{"description":"https://access.redhat.com/security/updates/classification/#moderate","type":"External","url":"https://access.redhat.com/security/updates/classification/#moderate"}]},"aggregate_severity":"Moderate","document_tracking":{"initial_release_date":"2020-10-28T18:24:00Z","identification":{"id":"RHSA-2020:4390"},"revision_history":{"revision":{"date":"2020-10-28T18:24:00Z","number":"1","description":"Current version"}},"generator":{"date":"2021-08-23T04:49:00Z","engine":"Red Hat SDEngine 3.0.0"},"current_release_date":"2020-10-28T18:24:00Z","version":"1","status":"Final"},"product_tree":{"relationship":[{"relates_to_product_reference":"7Server-7.6.EUS-RH7-RHOS-13.0","product_reference":"python-django-0:1.11.27-1.el7ost","full_product_name":{"product_id":"7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost","cpe":"cpe:/a:redhat:openstack:13::el7","product_name":"python-django-0:1.11.27-1.el7ost as a component of Red Hat OpenStack Platform 13.0 for RHEL 7.6 EUS Server"},"relation_type":"Default Component Of"},{"relates_to_product_reference":"7Server-RH7-RHOS-13.0","product_reference":"python-django-0:1.11.27-1.el7ost","full_product_name":{"product_id":"7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost","cpe":"cpe:/a:redhat:openstack:13::el7","product_name":"python-django-0:1.11.27-1.el7ost as a component of Red Hat OpenStack Platform 13.0"},"relation_type":"Default Component Of"}],"branch":[{"name":"Red Hat OpenStack Platform","type":"Product Family","branch":[{"name":"Red Hat OpenStack Platform 13.0 for RHEL 7.6 EUS Server","full_product_name":{"product_id":"7Server-7.6.EUS-RH7-RHOS-13.0","cpe":"cpe:/a:redhat:openstack:13::el7","product_name":"Red Hat OpenStack Platform 13.0 for RHEL 7.6 EUS Server"},"type":"Product Name"},{"name":"Red Hat OpenStack Platform 13.0","full_product_name":{"product_id":"7Server-RH7-RHOS-13.0","cpe":"cpe:/a:redhat:openstack:13::el7","product_name":"Red Hat OpenStack Platform 13.0"},"type":"Product Name"}]},{"name":"python-django-0:1.11.27-1.el7ost","full_product_name":{"product_id":"python-django-0:1.11.27-1.el7ost","cpe":"cpe:/a:redhat:openstack:13::el7","product_name":"python-django-1.11.27-1.el7ost.src.rpm"},"type":"Product Version"}]},"document_publisher":{"issuing_authority":"Red Hat Product Security","contact_details":"secalert@redhat.com","type":"Vendor"},"vulnerability":[{"notes":{"note":"Django: Incorrect HTTP detection with reverse-proxy connecting via HTTPS"},"cve":"CVE-2019-12781","references":{"reference":[{"description":"https://www.djangoproject.com/weblog/2019/jul/01/security-releases/","url":"https://www.djangoproject.com/weblog/2019/jul/01/security-releases/"},{"description":"CVE-2019-12781","url":"https://access.redhat.com/security/cve/CVE-2019-12781"},{"description":"bz#1724497: CVE-2019-12781 Django: Incorrect HTTP detection with reverse-proxy connecting via HTTPS","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1724497"}]},"release_date":"2019-07-01T00:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost","7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2020:4390"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank the Django project for reporting this issue. Upstream acknowledges Gavin Wahl as the original reporter."}},"discovery_date":"2019-06-24T00:00:00Z","ordinal":"1"},{"notes":{"note":"Django: backtracking in a regular expression in django.utils.text.Truncator leads to DoS"},"cve":"CVE-2019-14232","references":{"reference":[{"description":"https://www.djangoproject.com/weblog/2019/aug/01/security-releases/","url":"https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"},{"description":"CVE-2019-14232","url":"https://access.redhat.com/security/cve/CVE-2019-14232"},{"description":"bz#1734405: CVE-2019-14232 Django: backtracking in a regular expression in django.utils.text.Truncator leads to DoS","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1734405"}]},"release_date":"2019-08-01T08:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost","7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2020:4390"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank the Django project for reporting this issue."}},"discovery_date":"2019-07-25T00:00:00Z","ordinal":"2"},{"notes":{"note":"Django: the behavior of the underlying HTMLParser leading to DoS"},"cve":"CVE-2019-14233","references":{"reference":[{"description":"https://www.djangoproject.com/weblog/2019/aug/01/security-releases/","url":"https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"},{"description":"CVE-2019-14233","url":"https://access.redhat.com/security/cve/CVE-2019-14233"},{"description":"bz#1734410: CVE-2019-14233 Django: the behavior of the underlying HTMLParser leading to DoS","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1734410"}]},"release_date":"2019-08-01T08:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost","7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2020:4390"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank the Django project for reporting this issue."}},"discovery_date":"2019-07-25T00:00:00Z","ordinal":"3"},{"notes":{"note":"Django: SQL injection possibility in key and index lookups for JSONField/HStoreField"},"cve":"CVE-2019-14234","references":{"reference":[{"description":"https://www.djangoproject.com/weblog/2019/aug/01/security-releases/","url":"https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"},{"description":"CVE-2019-14234","url":"https://access.redhat.com/security/cve/CVE-2019-14234"},{"description":"bz#1734417: CVE-2019-14234 Django: SQL injection possibility in key and index lookups for JSONField/HStoreField","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1734417"}]},"release_date":"2019-08-01T08:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost","7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2020:4390"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank the Django project for reporting this issue."}},"discovery_date":"2019-07-25T00:00:00Z","ordinal":"4"},{"notes":{"note":"Django: Potential memory exhaustion in django.utils.encoding.uri_to_iri()"},"cve":"CVE-2019-14235","references":{"reference":[{"description":"https://www.djangoproject.com/weblog/2019/aug/01/security-releases/","url":"https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"},{"description":"CVE-2019-14235","url":"https://access.redhat.com/security/cve/CVE-2019-14235"},{"description":"bz#1734422: CVE-2019-14235 Django: Potential memory exhaustion in django.utils.encoding.uri_to_iri()","url":"https://bugzilla.redhat.com/show_bug.cgi?id=1734422"}]},"release_date":"2019-08-01T08:00:00Z","involvements":{"involvement":{"party":"Vendor","status":"Completed"}},"product_statuses":{"status":{"product_id":["7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost","7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"],"type":"Fixed"}},"remediations":{"remediation":{"description":"For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\nhttps://access.redhat.com/articles/11258","type":"Vendor Fix","url":"https://access.redhat.com/errata/RHSA-2020:4390"}},"threats":{"threat":{"description":"Moderate","type":"Impact"}},"acknowledgments":{"acknowledgment":{"description":"Red Hat would like to thank the Django project for reporting this issue."}},"discovery_date":"2019-07-25T00:00:00Z","ordinal":"5"}],"document_notes":{"note":["An update for python-django is now available for Red Hat OpenStack Platform\n13 (Queens).\nRed Hat Product Security has rated this update as having a security impact\nof Moderate. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available for each vulnerability from\nthe CVE link(s) in the References section.","Django is a high-level Python Web framework that encourages rapid\ndevelopment and a clean, pragmatic design. It focuses on automating as much\nas possible and adhering to the DRY (Don't Repeat Yourself) principle.\nSecurity Fix(es):\n* Incorrect HTTP detection with reverse-proxy connecting via HTTPS\n(CVE-2019-12781)\n* backtracking in a regular expression in django.utils.text.Truncator leads\nto DoS (CVE-2019-14232)\n* the behavior of the underlying HTMLParser leading to DoS (CVE-2019-14233)\n* SQL injection possibility in key and index lookups for\nJSONField/HStoreField (CVE-2019-14234)\n* Potential memory exhaustion in django.utils.encoding.uri_to_iri()\n(CVE-2019-14235)\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.","This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original."]},"document_type":"Security Advisory"}}